'use strict';

/**
 * Invoice Payment Service
 *
 * Settle an outstanding subscription invoice (monthly renewal, proration, or an
 * add-on) with bKash. Mirrors the top-up flow but pays an existing Invoice row
 * instead of crediting conversations:
 *   1. initiateInvoicePayment()  — start bKash checkout for a specific pending invoice
 *   2. initiateRenewalPayment()  — ensure a monthly invoice exists, then start checkout
 *   3. completeInvoicePayment()  — execute the bKash payment, mark the invoice paid,
 *                                  and (re)activate the subscription's AI if recurring
 *
 * Founder billing model: a monthly ৳999 invoice is auto-issued on renewal with a
 * 3-day due window; paying it (re)activates the subscription so the AI resumes.
 * The bKash paymentID is round-tripped through the FE (as the top-up flow does), so
 * nothing transient needs to be persisted server-side.
 */

const { Subscription, Invoice, Shop } = require('../entities');
const BangladeshPaymentService = require('../payment/bangladesh-payment.service');
const subscriptionService = require('./subscription.service');
const { AppError } = require('../../utils/AppError');
const { createLogger } = require('../../utils/structured-logger');

const logger = createLogger('InvoicePaymentService');
const bdPayment = new BangladeshPaymentService();

// Invoice.status ENUM is ('pending','paid','cancelled','overdue') — these two are payable.
const PAYABLE_STATUSES = ['pending', 'overdue'];
const { RECURRING_INVOICE_TYPES } = require('./subscription.plans');

/**
 * Load an invoice that belongs to the shop and is in a payable state.
 */
const loadPayableInvoice = async (shopId, invoiceId) => {
    const invoice = await Invoice.findOne({ where: { id: invoiceId, shop_id: shopId } });
    if (!invoice) throw new AppError('Invoice not found', 404);
    if (invoice.status === 'paid') throw new AppError('Invoice is already paid', 409);
    if (!PAYABLE_STATUSES.includes(invoice.status)) {
        throw new AppError(`Invoice cannot be paid (status: ${invoice.status})`, 400);
    }
    return invoice;
};

/**
 * Start a bKash checkout for a specific outstanding invoice.
 *
 * @param {string} shopId
 * @param {string} invoiceId
 * @param {{ phone?: string, name?: string, callbackUrl: string }} customerInfo
 * @returns {{ invoice_id, invoice_number, amount, bkash_url, payment_id }}
 */
const initiateInvoicePayment = async (shopId, invoiceId, { phone, name, callbackUrl }) => {
    if (!callbackUrl) throw new AppError('callback_url is required', 400);

    const invoice = await loadPayableInvoice(shopId, invoiceId);
    const amount = parseFloat(invoice.amount);
    if (!(amount > 0)) throw new AppError('Invoice amount is not payable', 400);

    const shop = await Shop.findByPk(shopId);

    const bkashResult = await bdPayment.initializeBkashPayment({
        order_id: invoice.invoice_number,
        amount,
        customer_name: name || shop?.name || 'Shop Owner',
        customer_phone: phone || shop?.phone || '01000000000',
        callback_url: callbackUrl,
        shop_id: shopId
    });

    if (!bkashResult.success) {
        throw new AppError('bKash payment initiation failed', 502);
    }

    logger.info('Invoice payment initiated', {
        shopId, invoiceId, invoiceNumber: invoice.invoice_number, bkashPaymentId: bkashResult.payment_id
    });

    return {
        invoice_id: invoice.id,
        invoice_number: invoice.invoice_number,
        amount,
        bkash_url: bkashResult.bkash_url,
        payment_id: bkashResult.payment_id
    };
};

/**
 * Ensure a monthly renewal invoice exists for the shop, then start a bKash checkout.
 * Used by the primary "Activate / Renew with bKash" CTA so a lapsed/trial owner can
 * convert even when no invoice was generated by the monthly cron yet.
 *
 * @param {string} shopId
 * @param {string} userId
 * @param {{ phone?: string, name?: string, callbackUrl: string }} customerInfo
 */
const initiateRenewalPayment = async (shopId, userId, customerInfo) => {
    const invoice = await subscriptionService.ensureRenewalInvoice(shopId, userId);
    return initiateInvoicePayment(shopId, invoice.id, customerInfo);
};

/**
 * Execute the bKash payment and settle the invoice.
 * On success marks the invoice paid; recurring invoices also (re)activate the AI.
 *
 * @param {string} shopId
 * @param {string} invoiceId
 * @param {string} bkashPaymentId - paymentID returned by bKash (round-tripped from FE)
 * @returns {{ success, invoice_id, status, transaction_id, subscription_status }}
 */
const completeInvoicePayment = async (shopId, invoiceId, bkashPaymentId) => {
    const invoice = await Invoice.findOne({ where: { id: invoiceId, shop_id: shopId } });
    if (!invoice) throw new AppError('Invoice not found', 404);

    if (invoice.status === 'paid') {
        return { success: true, already_paid: true, invoice_id: invoice.id, status: 'paid' };
    }

    if (!bkashPaymentId) throw new AppError('payment_id is required', 400);

    const verification = await bdPayment.verifyBkashPayment(bkashPaymentId);

    if (!verification.success || verification.status !== 'completed') {
        // Leave the invoice payable so the owner can retry (status ENUM has no 'failed').
        throw new AppError(verification.message || 'bKash payment verification failed', 402);
    }

    await invoice.update({
        status: 'paid',
        paid_at: new Date(),
        payment_method: 'bkash',
        transaction_id: verification.transaction_id
    });

    // Recurring (monthly / partner) invoice → (re)activate the AI. One-off invoices
    // (proration, add-ons) just settle; they never gate AI.
    let subscriptionStatus = null;
    if (RECURRING_INVOICE_TYPES.includes(invoice.invoice_type)) {
        const subscription = await Subscription.findOne({ where: { id: invoice.subscription_id } });
        if (subscription) {
            await subscriptionService.activateFromPaidInvoice(subscription);
            subscriptionStatus = subscription.status;
        }
    }

    logger.info('Invoice payment completed', {
        shopId, invoiceId, trxId: verification.transaction_id, subscriptionStatus
    });

    return {
        success: true,
        invoice_id: invoice.id,
        status: 'paid',
        transaction_id: verification.transaction_id,
        subscription_status: subscriptionStatus
    };
};

module.exports = {
    initiateInvoicePayment,
    initiateRenewalPayment,
    completeInvoicePayment
};
